direction = 270;
speed = random_range(1,10);
gravity = 1;
scal = random_range(.1,1);
image_alpha -= random_range(.05,.1);
image_xscale = scal;
image_yscale = scal;
image_angle = random(359)
ang = choose(1, -1, 2, -2);